version: "3.8"

services:
    samba:
        build: image
        volumes:
            - type: bind
              source: "$RUN_MOUNT"
              target: "/mount"
        ports:
            - "$RUN_PORT:445"
        restart_policy: 
            condition: on-failure
        environment: 
            - "RUN_UID=${RUN_UID}"
            - "RUN_GID=${RUN_GID}"
        # Required for selinux context passthrough.
        privileged: true
